---
- name: Deploy metallb pool
  include_tasks: metallb.yml
  tags: metallb
  when: k3s_control_node

- name: Remove tmp directory used for manifests
  file:
    path: /tmp/k3s
    state: absent
  when: k3s_control_node