apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.232.53.188-172.232.53.188
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pool-advertisment
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
